### ISSUE TITLE
Initialize members

### ISSUE THREAD

**Issue by flavius** [mihai-op/TicTacToe#15]
https://github.com/mihai-op/TicTacToe/blob/ad6de1f93de91400656d240ec1b8881b035ec030/src/Game.php#L7

This should be initialized to an empty array, preferably in the definition of the class.

Otherwise in strict mode you might get warnings for lines like

`$this->players[0] = 1;`

Also: make sure you run php and phpunit in strict mode.

And also: check and fix this type of mistake everywhere in the code.

**Comment by mihai-op** [comment]
Could you please detail what does 'strict' mode mean (for both php and phpunit)?

All I can find on Internet is about inserting `declare(strict_types=1);` at the beginning of every file.

**Comment by flavius** [comment]
http://www.phptherightway.com/#error_reporting, but also look over that entire site, it's helpful.
