### ISSUE TITLE
Tests serve as documentation

### ISSUE THREAD

**Issue by flavius** [mihai-op/TicTacToe#2]
In real projects, we don't usually have time to write (and more importantly, maintain) the documentation of the project.

One of the advantages of tests is that they can serve as documentation. In fact, they're far superior to any form of documentation, because you can run them and if they pass (and test coverage is a measurement for the confidence in the test results), it means your code is properly documented.

Tests are a verifiable form of documentation.

In order to use this advantage of tests to its fullest, you have to make testing code expressive.

A line like

`$game = new Game(true);`

doesn't tell me what exactly is `true` supposed to mean.

Look over your tests and improve semantic expressiveness of the tests, such that ideas are better conveyed.

**Comment by mihai-op** [comment]
Issue is too general, I will keep thinking about it.

For your example I proposed a solution in the tests (a static method explicitely named for its purpose).

Please give feedback.

**Comment by mihai-op** [comment]
Closed until further notice.
