### ISSUE TITLE
Methods should always explicitly return a value of the proper type

### ISSUE THREAD

**Issue by flavius** [mihai-op/TicTacToe#5]
A method should always return a value, and not rely on the default return value `NULL` either.

For example, this method:

https://github.com/mihai-op/TicTacToe/blob/32bd462fcaee2da395e29390bf6ecb75dcb41b6c/src/Board.php#L66

Fix this throughout the entire code base.

**Comment by mihai-op** [comment]
I reopened this issue because I need more clarification on how to handle return values for methods like Game::markOnBoard, where there is no practical meaning in return anything.

**Comment by flavius** [comment]
If I understand correctly the intention with that code, that method is meant to return void, so I would just leave it with no return statement.
